import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components";
import { cn } from "@/lib/utils";
import { Dialog } from "@/components/ui/dialog";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-slate-100 p-4")}>
        <Dialog>
          <NavBar />
          {children}
        </Dialog>
      </body>
    </html>
  );
}
